# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
  branches:
    exclude:
    - '*' # Only run when a PR is created

pr:
- main # Run when we PR to main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build API'
  inputs:
    command: build
    projects: '$(System.DefaultWorkingDirectory)/CalculatorApi.sln'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: test
    arguments: '--logger:trx'
    testRunTitle: 'Unit tests for build $(Build.BuildId)'
    projects: '$(System.DefaultWorkingDirectory)/CalculatorApi.UnitTests/CalculatorApi.UnitTests.csproj'
